Repository taco-xyz/tacoq, pull requests merged in 2025-03, with the labels that each got.

#81 feat: Add serializable exception type
  client_sdks/python/src/models/exception.py
  client_sdks/python/src/tacoq.egg-info/SOURCES.txt
  client_sdks/python/src/worker/client.py
  client_sdks/python/tests/e2e/test_full.py
Labels: enhancement

#83 Python SDK Test Improvements
  client_sdks/python/pyproject.toml
  client_sdks/python/src/broker/client.py
  client_sdks/python/src/logger_manager.py
  client_sdks/python/src/manager/client.py
  client_sdks/python/src/tacoq.egg-info/PKG-INFO
  client_sdks/python/src/tacoq.egg-info/requires.txt
  client_sdks/python/src/worker/client.py
  client_sdks/python/tests/benchmarks/README.md
  client_sdks/python/tests/benchmarks/test_task_creation.py
  client_sdks/python/tests/conftest.py
  client_sdks/python/tests/e2e/test_full.py
  client_sdks/python/tests/unit/manager/test_health.py
  client_sdks/python/tests/unit/manager/test_tasks.py
  client_sdks/python/tests/unit/publisher/test_publisher_client.py
  client_sdks/python/tests/unit/worker/test_worker_client.py
  client_sdks/python/uv.lock
Labels: bug, enhancement

#86 Relay Client Improvements
  client_sdks/python/examples/config.py
  client_sdks/python/src/core/infra/broker/client.py
  client_sdks/python/src/core/infra/manager/__init__.py
  client_sdks/python/src/core/infra/manager/client.py
  client_sdks/python/src/core/infra/relay/__init__.py
  client_sdks/python/src/core/infra/relay/client.py
  client_sdks/python/src/core/infra/relay/config.py
  client_sdks/python/src/core/models/exception.py
  client_sdks/python/src/core/models/task.py
  client_sdks/python/src/publisher/client.py
  client_sdks/python/src/worker/client.py
  client_sdks/python/src/worker/config.py
  client_sdks/python/tests/conftest.py
  client_sdks/python/tests/e2e/test_full.py
  client_sdks/python/tests/unit/manager/test_health.py
  client_sdks/python/tests/unit/manager/test_tasks.py
  client_sdks/python/tests/unit/publisher/test_publisher_client.py
  client_sdks/python/tests/unit/worker/test_worker_client.py
  server/relay/src/constants.rs
  server/relay/src/main.rs
Labels: documentation, enhancement

#90 chore: Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#87 Improve examples
  client_sdks/python/READMD.md
  client_sdks/python/README.md
  client_sdks/python/examples/config.py
  client_sdks/python/examples/example_producer.py
  client_sdks/python/examples/example_worker.py
  client_sdks/python/pyproject.toml
  client_sdks/python/src/tacoq/publisher/__init__.py
  client_sdks/python/src/tacoq/worker/cli/__init__.py
  client_sdks/python/tacoq.egg-info/PKG-INFO
  client_sdks/python/tacoq.egg-info/SOURCES.txt
  client_sdks/python/tacoq.egg-info/dependency_links.txt
  client_sdks/python/tacoq.egg-info/entry_points.txt
  client_sdks/python/tacoq.egg-info/requires.txt
  client_sdks/python/tacoq.egg-info/top_level.txt
  client_sdks/python/tacoq/__init__.py
  client_sdks/python/tacoq/core/infra/broker/__init__.py
  client_sdks/python/tacoq/core/infra/broker/client.py
  client_sdks/python/tacoq/core/infra/broker/config.py
  client_sdks/python/tacoq/core/infra/relay/__init__.py
  client_sdks/python/tacoq/core/infra/relay/client.py
  client_sdks/python/tacoq/core/infra/relay/config.py
  client_sdks/python/tacoq/core/models/__init__.py
  client_sdks/python/tacoq/core/models/exception.py
  client_sdks/python/tacoq/core/models/task.py
  client_sdks/python/tacoq/core/telemetry/__init__.py
  client_sdks/python/tacoq/core/telemetry/logger_manager.py
  client_sdks/python/tacoq/core/telemetry/tracer_manager.py
  client_sdks/python/tacoq/publisher/__init__.py
  client_sdks/python/tacoq/publisher/client.py
  client_sdks/python/tacoq/worker/__init__.py
  client_sdks/python/tacoq/worker/cli/__init__.py
  client_sdks/python/tacoq/worker/cli/cli.py
  client_sdks/python/tacoq/worker/cli/importer.py
  client_sdks/python/tacoq/worker/cli/logger.py
  client_sdks/python/tacoq/worker/cli/reloader.py
  client_sdks/python/tacoq/worker/cli/runner.py
  client_sdks/python/tacoq/worker/client.py
  client_sdks/python/tacoq/worker/config.py
  client_sdks/python/tests/conftest.py
  client_sdks/python/tests/e2e/test_full.py
  client_sdks/python/tests/unit/manager/test_health.py
  client_sdks/python/tests/unit/manager/test_tasks.py
  client_sdks/python/tests/unit/publisher/test_publisher_client.py
  client_sdks/python/tests/unit/worker/test_worker_client.py
  client_sdks/python/uv.lock
  examples/README.md
  examples/infrastructure/all-in-one/.env.example
  examples/infrastructure/all-in-one/docker-compose.yml
  examples/infrastructure/full/.env.example
  examples/infrastructure/full/docker-compose.yml
  examples/infrastructure/full/grafana-datasources.yaml
  examples/infrastructure/full/tempo.yaml
  examples/sdks/python/1-simple-example/.python-version
  examples/sdks/python/1-simple-example/README.md
  examples/sdks/python/1-simple-example/publisher_app.py
  examples/sdks/python/1-simple-example/pyproject.toml
  examples/sdks/python/1-simple-example/telemetry.py
  examples/sdks/python/1-simple-example/uv.lock
  examples/sdks/python/1-simple-example/worker_app.py
  examples/sdks/python/README.md
Labels: documentation

#98 docs: Bump example tacoq version
  Cargo.lock
  examples/sdks/python/1-simple-example/pyproject.toml
  examples/sdks/python/1-simple-example/uv.lock
Labels: documentation

#101 feat: Decouple relay from publisher
  README.md
  client_sdks/python/tacoq.egg-info/PKG-INFO
  client_sdks/python/tacoq.egg-info/SOURCES.txt
  client_sdks/python/tacoq.egg-info/dependency_links.txt
  client_sdks/python/tacoq.egg-info/entry_points.txt
  client_sdks/python/tacoq.egg-info/requires.txt
  client_sdks/python/tacoq.egg-info/top_level.txt
  client_sdks/python/tacoq/__init__.py
  client_sdks/python/tacoq/core/infra/broker/config.py
  client_sdks/python/tacoq/core/infra/relay/__init__.py
  client_sdks/python/tacoq/publisher/client.py
  client_sdks/python/tacoq/relay/__init__.py
  client_sdks/python/tacoq/relay/client.py
  client_sdks/python/tacoq/relay/config.py
  client_sdks/python/tacoq/worker/client.py
  client_sdks/python/tests/conftest.py
  client_sdks/python/tests/e2e/test_full.py
  client_sdks/python/tests/unit/manager/test_health.py
  client_sdks/python/tests/unit/manager/test_tasks.py
  client_sdks/python/tests/unit/publisher/test_publisher_client.py
  client_sdks/python/tests/unit/worker/test_worker_client.py
Labels: enhancement

#105 feat: Add task processing update
  client_sdks/python/tacoq/core/infra/broker/client.py
  client_sdks/python/tacoq/worker/client.py
Labels: enhancement

#104 feat: Improve environment variable names
  .gitignore
  README.md
  client_sdks/docker-compose.test.yml
  dev/config/grafana-datasources.yaml
  dev/config/tempo.yaml
  dev/docker-compose.yml
  examples/infrastructure/full/.env.example
  server/relay/.env.sample
  server/relay/Dockerfile
  server/relay/src/config.rs
  server/relay/src/main.rs
Labels: enhancement

#106 Docs/responsiveness
  docs/src/app/components/Footer.tsx
  docs/src/app/components/Logo.tsx
  docs/src/app/components/PageLinksBar.tsx
  docs/src/app/components/breadcrumbs/Breadcrumbs.tsx
  docs/src/app/components/docs-page-layout/DocsPageLayout.tsx
  docs/src/app/components/docs-page-layout/breadcrumbs/Breadcrumbs.tsx
  docs/src/app/components/heading/Heading.tsx
  docs/src/app/components/sidebar/DesktopSideBar.tsx
  docs/src/app/components/sidebar/MobileSidebarButton.tsx
  docs/src/app/components/sidebar/MobileSidebarPortal.tsx
  docs/src/app/components/sidebar/components/Anchor.tsx
  docs/src/app/components/sidebar/components/Tooltip.tsx
  docs/src/app/components/sidebar/components/page/DesktopPage.tsx
  docs/src/app/components/sidebar/components/page/MobilePage.tsx
  docs/src/app/components/sidebar/components/page/components/Highlight.tsx
  docs/src/app/components/sidebar/context/MobileSidebarModalContext.tsx
  docs/src/app/components/sidebar/context/PageNavigationContext.tsx
  docs/src/app/components/sidebar/context/TooltipContext.tsx
  docs/src/app/components/topbar/TopBar.tsx
  docs/src/app/components/topbar/components/ThemeToggle.tsx
  docs/src/app/components/topbar/components/search/components/DesktopSearchButton.tsx
  docs/src/app/components/topbar/components/search/components/MobileSearchButton.tsx
  docs/src/app/components/topbar/components/search/components/SearchPortal.tsx
  docs/src/app/components/topbar/components/search/context/SearchModalContext.tsx
  docs/src/app/globals.css
  docs/src/app/layout.tsx
  docs/src/contexts/PageTreeContext.tsx
Labels: enhancement

#91 Documentation
  docs/src/app/components/sidebar/DesktopSideBar.tsx
  docs/src/app/getting-started/editing/local/page.mdx
  docs/src/app/getting-started/editing/page.mdx
  docs/src/app/getting-started/editing/web/page.mdx
  docs/src/app/getting-started/migration/page.mdx
  docs/src/app/getting-started/navigation/page.mdx
  docs/src/app/getting-started/quickstart/page.mdx
  docs/src/app/getting-started/settings/page.mdx
  docs/src/app/page.mdx
  docs/src/app/quickstart/core-concepts/page.mdx
  docs/src/app/quickstart/setup/page.mdx
  docs/src/app/technical-reference/system-architecture/page.mdx
  docs/src/app/technical-reference/versioning/page.mdx
  docs/src/app/writing/code/page.mdx
  docs/src/app/writing/headers-and-text/page.mdx
  docs/src/app/writing/images/page.mdx
  docs/src/app/writing/links/page.mdx
  docs/src/app/writing/lists/page.mdx
  docs/src/app/writing/metadata/page.mdx
  docs/src/app/writing/page-titles/page.mdx
  docs/src/app/writing/tables/page.mdx
  docs/src/contexts/PageTreeContext.tsx
Labels: documentation

#112 feat: Add custom code snippet component
  docs/mdx-components.tsx
  docs/next.config.ts
  docs/package.json
  docs/src/app/globals.css
  docs/src/app/layout.tsx
  docs/src/app/technical-reference/benchmarking/page.mdx
  docs/src/components/mdx/heading/Heading.tsx
  docs/src/components/mdx/heading/components/CopyLinkButton.tsx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/Logo.tsx
  docs/src/components/react/PageLinksBar.tsx
  docs/src/components/react/docs-page-layout/DocsPageLayout.tsx
  docs/src/components/react/docs-page-layout/breadcrumbs/Breadcrumbs.tsx
  docs/src/components/react/icons/social/DiscordIcon.tsx
  docs/src/components/react/icons/social/GithubIcon.tsx
  docs/src/components/react/icons/social/LinkedInIcon.tsx
  docs/src/components/react/icons/social/XIcon.tsx
  docs/src/components/react/icons/social/index.ts
  docs/src/components/react/sidebar/DesktopSideBar.tsx
  docs/src/components/react/sidebar/MobileSidebarButton.tsx
  docs/src/components/react/sidebar/MobileSidebarPortal.tsx
  docs/src/components/react/sidebar/components/Anchor.tsx
  docs/src/components/react/sidebar/components/Tooltip.tsx
  docs/src/components/react/sidebar/components/page/DesktopPage.tsx
  docs/src/components/react/sidebar/components/page/Highlight.tsx
  docs/src/components/react/sidebar/components/page/MobilePage.tsx
  docs/src/components/react/sidebar/components/page/components/Highlight.tsx
  docs/src/components/react/sidebar/context/MobileSidebarModalContext.tsx
  docs/src/components/react/sidebar/context/PageNavigationContext.tsx
  docs/src/components/react/sidebar/context/TooltipContext.tsx
  docs/src/components/react/topbar/TopBar.tsx
  docs/src/components/react/topbar/components/GitHubLink.tsx
  docs/src/components/react/topbar/components/ThemeToggle.tsx
  docs/src/components/react/topbar/components/search/components/DesktopSearchButton.tsx
  docs/src/components/react/topbar/components/search/components/MobileSearchButton.tsx
  docs/src/components/react/topbar/components/search/components/SearchPortal.tsx
  docs/src/components/react/topbar/components/search/context/SearchModalContext.tsx
  docs/src/contexts/PageTreeContext.tsx
  docs/tsconfig.json
  docs/yarn.lock
Labels: enhancement

#113 Docs/callout
  docs/mdx-components.tsx
  docs/src/app/globals.css
  docs/src/app/layout.tsx
  docs/src/app/not-found.tsx
  docs/src/app/technical-reference/benchmarking/page.mdx
  docs/src/components/mdx/Blockquotes.tsx
  docs/src/components/mdx/heading/Heading.tsx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/Logo.tsx
  docs/src/components/react/PageLinksBar.tsx
  docs/src/components/react/docs-page-layout/DocsPageLayout.tsx
  docs/src/components/react/docs-page-layout/breadcrumbs/Breadcrumbs.tsx
  docs/src/components/react/sidebar/components/Tooltip.tsx
  docs/src/components/react/sidebar/components/page/DesktopPage.tsx
  docs/src/components/react/sidebar/components/page/MobilePage.tsx
Labels: enhancement

#116 Update favicon.ico
  docs/src/app/favicon.ico
Labels: enhancement

#119 Docs CLI
  docs/package.json
  docs/src/app/guides/horizontal-scaling/metadata.json
  docs/src/app/guides/maximizing-performance/metadata.json
  docs/src/app/guides/metadata.json
  docs/src/app/guides/same-app-worker-pattern/metadata.json
  docs/src/app/guides/task-versioning/metadata.json
  docs/src/app/quickstart/core-concepts/metadata.json
  docs/src/app/quickstart/metadata.json
  docs/src/app/quickstart/setup/metadata.json
  docs/src/app/technical-reference/benchmarks/metadata.json
  docs/src/app/technical-reference/metadata.json
  docs/src/app/technical-reference/relay-endpoints/metadata.json
  docs/src/app/technical-reference/system-architecture/metadata.json
  docs/src/app/technical-reference/versioning/metadata.json
  docs/src/cli-commands/regen.ts
  docs/src/cli.ts
  docs/src/components/react/PageLinksBar.tsx
  docs/src/components/react/docs-page-layout/DocsPageLayout.tsx
  docs/src/contexts/PageTreeContext.tsx
  docs/src/page-tree.json
  docs/src/types/PageTree.ts
  docs/src/utils/getHeaderId.ts
  docs/src/utils/getIcon.ts
  docs/tsconfig.json
  docs/yarn.lock
Labels: documentation, enhancement

#118 docs: Add TacoQ Banner
  TacoQBanner.png
Labels: documentation

#120 Add Banner and new Icons
  README.md
  banner.png
  docs/mdx-components.tsx
  docs/public/TacoDivisionLogoDark.svg
  docs/public/TacoDivisionLogoLight.svg
  docs/public/TacoDivisionTextLogoDark.svg
  docs/public/TacoDivisionTextLogoLight.svg
  docs/public/TacoQBannerDark.svg
  docs/public/TacoQBannerLight.svg
  docs/public/TacoQTextLogoDark.svg
  docs/public/TacoQTextLogoLight.svg
  docs/src/app/favicon.ico
  docs/src/app/layout.tsx
  docs/src/app/page.mdx
  docs/src/components/mdx/Card.tsx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/Logo.tsx
  docs/src/components/react/docs-page-layout/DocsPageLayout.tsx
  docs/src/components/react/topbar/TopBar.tsx
Labels: documentation, enhancement

#111 fix: Fix leftover tasks spamming the test console
  .gitignore
  client_sdks/python/tests/conftest.py
Labels: bug

#123 fix: Fix layout resize bug on route change
  docs/src/app/layout.tsx
Labels: bug, documentation

#124 Python Worker Improvements
  client_sdks/python/pyproject.toml
  client_sdks/python/tacoq/core/infra/broker/client.py
  client_sdks/python/tacoq/core/infra/broker/config.py
  client_sdks/python/tacoq/publisher/client.py
  client_sdks/python/tacoq/worker/client.py
  client_sdks/python/uv.lock
Labels: documentation, enhancement

#126 feat: Improve SEO
  docs/public/llms.txt
  docs/src/app/apple-icon.png
  docs/src/app/icon.ico
  docs/src/app/layout.tsx
  docs/src/app/opengraph-image.alt.txt
  docs/src/app/opengraph-image.png
  docs/src/app/quickstart/core-concepts/page.mdx
  docs/src/app/quickstart/setup/page.mdx
  docs/src/app/robots.ts
  docs/src/app/sitemap.ts
  docs/src/app/technical-reference/benchmarking/page.mdx
  docs/src/app/technical-reference/benchmarks/page.mdx
  docs/src/app/technical-reference/relay-endpoints/page.mdx
  docs/src/app/technical-reference/system-architecture/page.mdx
  docs/src/app/technical-reference/versioning/page.mdx
  docs/src/app/twitter-image.alt.txt
  docs/src/app/twitter-image.png
Labels: enhancement

#127 feat: Improve mobile and Mac compatability, add new icons, improve acessibility
  docs/mdx-components.tsx
  docs/package.json
  docs/public/TacoQBannerDark.png
  docs/public/TacoQBannerDark.svg
  docs/public/TacoQBannerLight.png
  docs/public/TacoQBannerLight.svg
  docs/src/app/globals.css
  docs/src/app/guides/horizontal-scaling/metadata.json
  docs/src/app/guides/maximizing-performance/metadata.json
  docs/src/app/guides/metadata.json
  docs/src/app/guides/same-app-worker-pattern/metadata.json
  docs/src/app/layout.tsx
  docs/src/app/not-found.tsx
  docs/src/app/page.mdx
  docs/src/app/quickstart/core-concepts/metadata.json
  docs/src/app/quickstart/metadata.json
  docs/src/app/quickstart/setup/metadata.json
  docs/src/app/technical-reference/benchmarks/metadata.json
  docs/src/app/technical-reference/metadata.json
  docs/src/app/technical-reference/relay-endpoints/metadata.json
  docs/src/app/technical-reference/system-architecture/metadata.json
  docs/src/app/technical-reference/system-architecture/page.mdx
  docs/src/app/technical-reference/versioning/metadata.json
  docs/src/components/mdx/Blockquotes.tsx
  docs/src/components/mdx/Card.tsx
  docs/src/components/mdx/heading/components/CopyLinkButton.tsx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/Logo.tsx
  docs/src/components/react/PageLinksBar.tsx
  docs/src/components/react/docs-page-layout/DocsPageLayout.tsx
  docs/src/components/react/docs-page-layout/breadcrumbs/Breadcrumbs.tsx
  docs/src/components/react/sidebar/DesktopSideBar.tsx
  docs/src/components/react/sidebar/MobileSidebarButton.tsx
  docs/src/components/react/sidebar/MobileSidebarPortal.tsx
  docs/src/components/react/sidebar/components/Tooltip.tsx
  docs/src/components/react/sidebar/components/page/DesktopPage.tsx
  docs/src/components/react/sidebar/components/page/MobilePage.tsx
  docs/src/components/react/sidebar/context/PageNavigationContext.tsx
  docs/src/components/react/topbar/components/ThemeToggle.tsx
  docs/src/components/react/topbar/components/search/components/DesktopSearchButton.tsx
  docs/src/components/react/topbar/components/search/components/MobileSearchButton.tsx
  docs/src/components/react/topbar/components/search/components/SearchPortal.tsx
  docs/src/components/react/topbar/components/search/context/SearchModalContext.tsx
  docs/src/contexts/PageTreeContext.tsx
  docs/src/contexts/PlatformContext.tsx
  docs/src/page-tree.json
  docs/src/utils/getIcon.ts
  docs/yarn.lock
Labels: documentation, enhancement

#131 Fix dead links and rework Footer and Theme Toggle styling
  docs/mdx-components.tsx
  docs/src/app/page.mdx
  docs/src/app/quickstart/core-concepts/page.mdx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/Logo.tsx
  docs/src/components/react/sidebar/MobileSidebarPortal.tsx
  docs/src/components/react/topbar/components/ThemeToggle.tsx
  docs/src/contexts/PageTreeContext.tsx
  docs/src/types/FooterContent.ts
Labels: documentation, enhancement

#130 docs: Relay Config + Versioning Update
  docs/src/app/technical-reference/benchmarks/metadata.json
  docs/src/app/technical-reference/relay-endpoints/metadata.json
  docs/src/app/technical-reference/relay-endpoints/page.mdx
  docs/src/app/technical-reference/relay-environment-vars/metadata.json
  docs/src/app/technical-reference/relay-environment-vars/page.mdx
  docs/src/app/technical-reference/system-architecture/metadata.json
  docs/src/app/technical-reference/system-architecture/page.mdx
  docs/src/app/technical-reference/versioning/metadata.json
  docs/src/app/technical-reference/versioning/page.mdx
  docs/src/page-tree.json
  docs/src/utils/getIcon.ts
Labels: documentation

#133 Fix Sidebar and Tooltip Issues
  docs/mdx-components.tsx
  docs/src/app/layout.tsx
  docs/src/app/sitemap.ts
  docs/src/components/mdx/Blockquotes.tsx
  docs/src/components/mdx/heading/Heading.tsx
  docs/src/components/mdx/heading/components/CopyLinkButton.tsx
  docs/src/components/react/Footer.tsx
  docs/src/components/react/sidebar/DesktopSideBar.tsx
  docs/src/components/react/sidebar/MobileSidebarPortal.tsx
  docs/src/components/react/sidebar/components/Tooltip.tsx
  docs/src/components/react/sidebar/context/TooltipContext.tsx
  docs/src/components/react/topbar/TopBar.tsx
  docs/src/components/react/topbar/components/search/components/SearchPortal.tsx
Labels: documentation, enhancement
